// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    DataPanel: typeof import('./src/components/DataPanel.vue')['default']
    DropdownComponent: typeof import('./src/components/DropdownComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSliderCustomZoom: typeof import('element-plus/es')['ElSliderCustomZoom']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavBurger: typeof import('./src/components/NavBurger.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
